/*
  # Add country_name column to projects table

  1. Changes
    - Add `country_name` column to `projects` table
    - Populate `country_name` for existing projects based on their `country` code
    - Set default value for new projects

  2. Details
    - Maps country codes (e.g., 'FR', 'US', 'GB') to full country names (e.g., 'France', 'United States', 'United Kingdom')
    - Uses data from countries_names_codes_flags.csv
    - Ensures backward compatibility with existing projects
*/

-- Add country_name column to projects table
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'projects' AND column_name = 'country_name'
  ) THEN
    ALTER TABLE projects ADD COLUMN country_name text;
  END IF;
END $$;

-- Populate country_name for existing projects based on country code
UPDATE projects
SET country_name = CASE country
  WHEN 'AD' THEN 'Andorra'
  WHEN 'AE' THEN 'United Arab Emirates'
  WHEN 'AF' THEN 'Afghanistan'
  WHEN 'AG' THEN 'Antigua and Barbuda'
  WHEN 'AI' THEN 'Anguilla'
  WHEN 'AL' THEN 'Albania'
  WHEN 'AM' THEN 'Armenia'
  WHEN 'AO' THEN 'Angola'
  WHEN 'AQ' THEN 'Antarctica'
  WHEN 'AR' THEN 'Argentina'
  WHEN 'AS' THEN 'American Samoa'
  WHEN 'AT' THEN 'Austria'
  WHEN 'AU' THEN 'Australia'
  WHEN 'AW' THEN 'Aruba'
  WHEN 'AX' THEN 'Åland Islands'
  WHEN 'AZ' THEN 'Azerbaijan'
  WHEN 'BA' THEN 'Bosnia and Herzegovina'
  WHEN 'BB' THEN 'Barbados'
  WHEN 'BD' THEN 'Bangladesh'
  WHEN 'BE' THEN 'Belgium'
  WHEN 'BF' THEN 'Burkina Faso'
  WHEN 'BG' THEN 'Bulgaria'
  WHEN 'BH' THEN 'Bahrain'
  WHEN 'BI' THEN 'Burundi'
  WHEN 'BJ' THEN 'Benin'
  WHEN 'BL' THEN 'Saint Barthélemy'
  WHEN 'BM' THEN 'Bermuda'
  WHEN 'BN' THEN 'Brunei Darussalam'
  WHEN 'BO' THEN 'Bolivia Plurinational State of'
  WHEN 'BQ' THEN 'Caribbean Netherlands'
  WHEN 'BR' THEN 'Brazil'
  WHEN 'BS' THEN 'Bahamas'
  WHEN 'BT' THEN 'Bhutan'
  WHEN 'BV' THEN 'Bouvet Island'
  WHEN 'BW' THEN 'Botswana'
  WHEN 'BY' THEN 'Belarus'
  WHEN 'BZ' THEN 'Belize'
  WHEN 'CA' THEN 'Canada'
  WHEN 'CC' THEN 'Cocos (Keeling) Islands'
  WHEN 'CD' THEN 'Congo the Democratic Republic of the'
  WHEN 'CF' THEN 'Central African Republic'
  WHEN 'CG' THEN 'Republic of the Congo'
  WHEN 'CH' THEN 'Switzerland'
  WHEN 'CI' THEN 'Côte d''Ivoire'
  WHEN 'CK' THEN 'Cook Islands'
  WHEN 'CL' THEN 'Chile'
  WHEN 'CM' THEN 'Cameroon'
  WHEN 'CN' THEN 'China (People''s Republic of China)'
  WHEN 'CO' THEN 'Colombia'
  WHEN 'CR' THEN 'Costa Rica'
  WHEN 'CU' THEN 'Cuba'
  WHEN 'CV' THEN 'Cape Verde'
  WHEN 'CW' THEN 'Curaçao'
  WHEN 'CX' THEN 'Christmas Island'
  WHEN 'CY' THEN 'Cyprus'
  WHEN 'CZ' THEN 'Czech Republic'
  WHEN 'DE' THEN 'Germany'
  WHEN 'DJ' THEN 'Djibouti'
  WHEN 'DK' THEN 'Denmark'
  WHEN 'DM' THEN 'Dominica'
  WHEN 'DO' THEN 'Dominican Republic'
  WHEN 'DZ' THEN 'Algeria'
  WHEN 'EC' THEN 'Ecuador'
  WHEN 'EE' THEN 'Estonia'
  WHEN 'EG' THEN 'Egypt'
  WHEN 'EH' THEN 'Western Sahara'
  WHEN 'ER' THEN 'Eritrea'
  WHEN 'ES' THEN 'Spain'
  WHEN 'ET' THEN 'Ethiopia'
  WHEN 'EU' THEN 'Europe'
  WHEN 'FI' THEN 'Finland'
  WHEN 'FJ' THEN 'Fiji'
  WHEN 'FK' THEN 'Falkland Islands (Malvinas)'
  WHEN 'FM' THEN 'Micronesia Federated States of'
  WHEN 'FO' THEN 'Faroe Islands'
  WHEN 'FR' THEN 'France'
  WHEN 'GA' THEN 'Gabon'
  WHEN 'GB-ENG' THEN 'England'
  WHEN 'GB-NIR' THEN 'Northern Ireland'
  WHEN 'GB-SCT' THEN 'Scotland'
  WHEN 'GB-WLS' THEN 'Wales'
  WHEN 'GB' THEN 'United Kingdom'
  WHEN 'GD' THEN 'Grenada'
  WHEN 'GE' THEN 'Georgia'
  WHEN 'GF' THEN 'French Guiana'
  WHEN 'GG' THEN 'Guernsey'
  WHEN 'GH' THEN 'Ghana'
  WHEN 'GI' THEN 'Gibraltar'
  WHEN 'GL' THEN 'Greenland'
  WHEN 'GM' THEN 'Gambia'
  WHEN 'GN' THEN 'Guinea'
  WHEN 'GP' THEN 'Guadeloupe'
  WHEN 'GQ' THEN 'Equatorial Guinea'
  WHEN 'GR' THEN 'Greece'
  WHEN 'GS' THEN 'South Georgia and the South Sandwich Islands'
  WHEN 'GT' THEN 'Guatemala'
  WHEN 'GU' THEN 'Guam'
  WHEN 'GW' THEN 'Guinea-Bissau'
  WHEN 'GY' THEN 'Guyana'
  WHEN 'HK' THEN 'Hong Kong'
  WHEN 'HM' THEN 'Heard Island and McDonald Islands'
  WHEN 'HN' THEN 'Honduras'
  WHEN 'HR' THEN 'Croatia'
  WHEN 'HT' THEN 'Haiti'
  WHEN 'HU' THEN 'Hungary'
  WHEN 'ID' THEN 'Indonesia'
  WHEN 'IE' THEN 'Ireland'
  WHEN 'IL' THEN 'Israel'
  WHEN 'IM' THEN 'Isle of Man'
  WHEN 'IN' THEN 'India'
  WHEN 'IO' THEN 'British Indian Ocean Territory'
  WHEN 'IQ' THEN 'Iraq'
  WHEN 'IR' THEN 'Iran Islamic Republic of'
  WHEN 'IS' THEN 'Iceland'
  WHEN 'IT' THEN 'Italy'
  WHEN 'JE' THEN 'Jersey'
  WHEN 'JM' THEN 'Jamaica'
  WHEN 'JO' THEN 'Jordan'
  WHEN 'JP' THEN 'Japan'
  WHEN 'KE' THEN 'Kenya'
  WHEN 'KG' THEN 'Kyrgyzstan'
  WHEN 'KH' THEN 'Cambodia'
  WHEN 'KI' THEN 'Kiribati'
  WHEN 'KM' THEN 'Comoros'
  WHEN 'KN' THEN 'Saint Kitts and Nevis'
  WHEN 'KP' THEN 'Korea Democratic People''s Republic of'
  WHEN 'KR' THEN 'Korea Republic of'
  WHEN 'KW' THEN 'Kuwait'
  WHEN 'KY' THEN 'Cayman Islands'
  WHEN 'KZ' THEN 'Kazakhstan'
  WHEN 'LA' THEN 'Laos (Lao People''s Democratic Republic)'
  WHEN 'LB' THEN 'Lebanon'
  WHEN 'LC' THEN 'Saint Lucia'
  WHEN 'LI' THEN 'Liechtenstein'
  WHEN 'LK' THEN 'Sri Lanka'
  WHEN 'LR' THEN 'Liberia'
  WHEN 'LS' THEN 'Lesotho'
  WHEN 'LT' THEN 'Lithuania'
  WHEN 'LU' THEN 'Luxembourg'
  WHEN 'LV' THEN 'Latvia'
  WHEN 'LY' THEN 'Libya'
  WHEN 'MA' THEN 'Morocco'
  WHEN 'MC' THEN 'Monaco'
  WHEN 'MD' THEN 'Moldova Republic of'
  WHEN 'ME' THEN 'Montenegro'
  WHEN 'MF' THEN 'Saint Martin'
  WHEN 'MG' THEN 'Madagascar'
  WHEN 'MH' THEN 'Marshall Islands'
  WHEN 'MK' THEN 'North Macedonia'
  WHEN 'ML' THEN 'Mali'
  WHEN 'MM' THEN 'Myanmar'
  WHEN 'MN' THEN 'Mongolia'
  WHEN 'MO' THEN 'Macao'
  WHEN 'MP' THEN 'Northern Mariana Islands'
  WHEN 'MQ' THEN 'Martinique'
  WHEN 'MR' THEN 'Mauritania'
  WHEN 'MS' THEN 'Montserrat'
  WHEN 'MT' THEN 'Malta'
  WHEN 'MU' THEN 'Mauritius'
  WHEN 'MV' THEN 'Maldives'
  WHEN 'MW' THEN 'Malawi'
  WHEN 'MX' THEN 'Mexico'
  WHEN 'MY' THEN 'Malaysia'
  WHEN 'MZ' THEN 'Mozambique'
  WHEN 'NA' THEN 'Namibia'
  WHEN 'NC' THEN 'New Caledonia'
  WHEN 'NE' THEN 'Niger'
  WHEN 'NF' THEN 'Norfolk Island'
  WHEN 'NG' THEN 'Nigeria'
  WHEN 'NI' THEN 'Nicaragua'
  WHEN 'NL' THEN 'Netherlands'
  WHEN 'NO' THEN 'Norway'
  WHEN 'NP' THEN 'Nepal'
  WHEN 'NR' THEN 'Nauru'
  WHEN 'NU' THEN 'Niue'
  WHEN 'NZ' THEN 'New Zealand'
  WHEN 'OM' THEN 'Oman'
  WHEN 'PA' THEN 'Panama'
  WHEN 'PE' THEN 'Peru'
  WHEN 'PF' THEN 'French Polynesia'
  WHEN 'PG' THEN 'Papua New Guinea'
  WHEN 'PH' THEN 'Philippines'
  WHEN 'PK' THEN 'Pakistan'
  WHEN 'PL' THEN 'Poland'
  WHEN 'PM' THEN 'Saint Pierre and Miquelon'
  WHEN 'PN' THEN 'Pitcairn'
  WHEN 'PR' THEN 'Puerto Rico'
  WHEN 'PS' THEN 'Palestine'
  WHEN 'PT' THEN 'Portugal'
  WHEN 'PW' THEN 'Palau'
  WHEN 'PY' THEN 'Paraguay'
  WHEN 'QA' THEN 'Qatar'
  WHEN 'RE' THEN 'Réunion'
  WHEN 'RO' THEN 'Romania'
  WHEN 'RS' THEN 'Serbia'
  WHEN 'RU' THEN 'Russian Federation'
  WHEN 'RW' THEN 'Rwanda'
  WHEN 'SA' THEN 'Saudi Arabia'
  WHEN 'SB' THEN 'Solomon Islands'
  WHEN 'SC' THEN 'Seychelles'
  WHEN 'SD' THEN 'Sudan'
  WHEN 'SE' THEN 'Sweden'
  WHEN 'SG' THEN 'Singapore'
  WHEN 'SH' THEN 'Saint Helena Ascension and Tristan da Cunha'
  WHEN 'SI' THEN 'Slovenia'
  WHEN 'SJ' THEN 'Svalbard and Jan Mayen Islands'
  WHEN 'SK' THEN 'Slovakia'
  WHEN 'SL' THEN 'Sierra Leone'
  WHEN 'SM' THEN 'San Marino'
  WHEN 'SN' THEN 'Senegal'
  WHEN 'SO' THEN 'Somalia'
  WHEN 'SR' THEN 'Suriname'
  WHEN 'SS' THEN 'South Sudan'
  WHEN 'ST' THEN 'Sao Tome and Principe'
  WHEN 'SV' THEN 'El Salvador'
  WHEN 'SX' THEN 'Sint Maarten (Dutch part)'
  WHEN 'SY' THEN 'Syrian Arab Republic'
  WHEN 'SZ' THEN 'Kingdom of Eswatini'
  WHEN 'TC' THEN 'Turks and Caicos Islands'
  WHEN 'TD' THEN 'Chad'
  WHEN 'TF' THEN 'French Southern Territories'
  WHEN 'TG' THEN 'Togo'
  WHEN 'TH' THEN 'Thailand'
  WHEN 'TJ' THEN 'Tajikistan'
  WHEN 'TK' THEN 'Tokelau'
  WHEN 'TL' THEN 'Timor-Leste'
  WHEN 'TM' THEN 'Turkmenistan'
  WHEN 'TN' THEN 'Tunisia'
  WHEN 'TO' THEN 'Tonga'
  WHEN 'TR' THEN 'Republic of Türkiye'
  WHEN 'TT' THEN 'Trinidad and Tobago'
  WHEN 'TV' THEN 'Tuvalu'
  WHEN 'TW' THEN 'Taiwan (Republic of China)'
  WHEN 'TZ' THEN 'Tanzania United Republic of'
  WHEN 'UA' THEN 'Ukraine'
  WHEN 'UG' THEN 'Uganda'
  WHEN 'UM' THEN 'US Minor Outlying Islands'
  WHEN 'US' THEN 'United States'
  WHEN 'UY' THEN 'Uruguay'
  WHEN 'UZ' THEN 'Uzbekistan'
  WHEN 'VA' THEN 'Holy See (Vatican City State)'
  WHEN 'VC' THEN 'Saint Vincent and the Grenadines'
  WHEN 'VE' THEN 'Venezuela Bolivarian Republic of'
  WHEN 'VG' THEN 'Virgin Islands British'
  WHEN 'VI' THEN 'Virgin Islands U.S.'
  WHEN 'VN' THEN 'Vietnam'
  WHEN 'VU' THEN 'Vanuatu'
  WHEN 'WF' THEN 'Wallis and Futuna Islands'
  WHEN 'WS' THEN 'Samoa'
  WHEN 'XK' THEN 'Kosovo'
  WHEN 'YE' THEN 'Yemen'
  WHEN 'YT' THEN 'Mayotte'
  WHEN 'ZA' THEN 'South Africa'
  WHEN 'ZM' THEN 'Zambia'
  WHEN 'ZW' THEN 'Zimbabwe'
  ELSE country
END
WHERE country_name IS NULL;