-- Cost reduction: NULL llm_responses.raw_response_data once extraction is done.
--
-- IMPORTANT — this migration is intentionally a NO-OP at container startup.
--
-- The original version ran a single bulk UPDATE over the entire (very large)
-- llm_responses table. The app's asyncpg connection has command_timeout=10s
-- (set for pool stability), so that UPDATE was cancelled after 10 seconds,
-- the migration aborted, and the container crash-looped (502 in production).
--
-- The FORWARD behaviour is already handled in code: update_competitors_batch
-- (app/services/supabase_db.py) NULLs raw_response_data on every row as it is
-- extracted, so new audits never accumulate the heavy column.
--
-- The HISTORICAL backfill is optional (pure storage reclaim) and must be run
-- MANUALLY in batches from the Supabase SQL editor (postgres role, no 10s
-- client timeout). Run this repeatedly until it reports 0 rows:
--
--   WITH c AS (
--     SELECT id FROM public.llm_responses
--     WHERE answer_competitors IS NOT NULL
--       AND raw_response_data  IS NOT NULL
--       AND citations          IS NOT NULL
--     LIMIT 5000
--   )
--   UPDATE public.llm_responses lr
--   SET raw_response_data = NULL
--   FROM c
--   WHERE lr.id = c.id;
--
-- Then, off-hours, reclaim disk:  VACUUM FULL public.llm_responses;  (or pg_repack)
--
-- This SELECT keeps the migration as a single, instant, always-succeeding
-- statement so the runner marks it applied and never retries the heavy UPDATE.
SELECT 1;
